
package cswebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CSReferralSoap", targetNamespace = "CSWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CSReferralSoap {


    /**
     * Searches for physicians by the given criteria in a xml String.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SearchPhysician", action = "CSWebService/SearchPhysician")
    @WebResult(name = "SearchPhysicianResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "SearchPhysician", targetNamespace = "CSWebService", className = "cswebservice.SearchPhysician")
    @ResponseWrapper(localName = "SearchPhysicianResponse", targetNamespace = "CSWebService", className = "cswebservice.SearchPhysicianResponse")
    public String searchPhysician(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

    /**
     * Returns Service Center detailed information given a center ID in a xml string.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetServiceCenterDetail", action = "CSWebService/GetServiceCenterDetail")
    @WebResult(name = "GetServiceCenterDetailResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetServiceCenterDetail", targetNamespace = "CSWebService", className = "cswebservice.GetServiceCenterDetail")
    @ResponseWrapper(localName = "GetServiceCenterDetailResponse", targetNamespace = "CSWebService", className = "cswebservice.GetServiceCenterDetailResponse")
    public String getServiceCenterDetail(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

    /**
     * Returns Center of Excellence detailed information given a center ID in a xml string.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCenterOfExcellenceDetail", action = "CSWebService/GetCenterOfExcellenceDetail")
    @WebResult(name = "GetCenterOfExcellenceDetailResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetCenterOfExcellenceDetail", targetNamespace = "CSWebService", className = "cswebservice.GetCenterOfExcellenceDetail")
    @ResponseWrapper(localName = "GetCenterOfExcellenceDetailResponse", targetNamespace = "CSWebService", className = "cswebservice.GetCenterOfExcellenceDetailResponse")
    public String getCenterOfExcellenceDetail(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

    /**
     * Returns Service Center detailed information given a center ID in a xml string.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPhysicianDetail", action = "CSWebService/GetPhysicianDetail")
    @WebResult(name = "GetPhysicianDetailResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetPhysicianDetail", targetNamespace = "CSWebService", className = "cswebservice.GetPhysicianDetail")
    @ResponseWrapper(localName = "GetPhysicianDetailResponse", targetNamespace = "CSWebService", className = "cswebservice.GetPhysicianDetailResponse")
    public String getPhysicianDetail(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

    /**
     * Returns a list of insurance companies.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInsuranceCompanies", action = "CSWebService/GetInsuranceCompanies")
    @WebResult(name = "GetInsuranceCompaniesResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetInsuranceCompanies", targetNamespace = "CSWebService", className = "cswebservice.GetInsuranceCompanies")
    @ResponseWrapper(localName = "GetInsuranceCompaniesResponse", targetNamespace = "CSWebService", className = "cswebservice.GetInsuranceCompaniesResponse")
    public String getInsuranceCompanies();

    /**
     * Returns a list of insurance types.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInsuranceTypes", action = "CSWebService/GetInsuranceTypes")
    @WebResult(name = "GetInsuranceTypesResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetInsuranceTypes", targetNamespace = "CSWebService", className = "cswebservice.GetInsuranceTypes")
    @ResponseWrapper(localName = "GetInsuranceTypesResponse", targetNamespace = "CSWebService", className = "cswebservice.GetInsuranceTypesResponse")
    public String getInsuranceTypes();

    /**
     * Returns a list of specialties.
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSpecialties", action = "CSWebService/GetSpecialties")
    @WebResult(name = "GetSpecialtiesResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetSpecialties", targetNamespace = "CSWebService", className = "cswebservice.GetSpecialties")
    @ResponseWrapper(localName = "GetSpecialtiesResponse", targetNamespace = "CSWebService", className = "cswebservice.GetSpecialtiesResponse")
    public String getSpecialties();

    /**
     * Returns a list of medical conditions.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMedicalConditions", action = "CSWebService/GetMedicalConditions")
    @WebResult(name = "GetMedicalConditionsResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetMedicalConditions", targetNamespace = "CSWebService", className = "cswebservice.GetMedicalConditions")
    @ResponseWrapper(localName = "GetMedicalConditionsResponse", targetNamespace = "CSWebService", className = "cswebservice.GetMedicalConditionsResponse")
    public String getMedicalConditions(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

    /**
     * Returns a list of centers resulting from the request parameters.
     * 
     * @param requestParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCenters", action = "CSWebService/GetCenters")
    @WebResult(name = "GetCentersResult", targetNamespace = "CSWebService")
    @RequestWrapper(localName = "GetCenters", targetNamespace = "CSWebService", className = "cswebservice.GetCenters")
    @ResponseWrapper(localName = "GetCentersResponse", targetNamespace = "CSWebService", className = "cswebservice.GetCentersResponse")
    public String getCenters(
        @WebParam(name = "requestParam", targetNamespace = "CSWebService")
        String requestParam);

}
