
package cswebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CSReferral Web Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CSReferral", targetNamespace = "CSWebService", wsdlLocation = "https://csmdfind.connextions.com/cedarsws/CSReferral.asmx?wsdl")
public class CSReferral
    extends Service
{

    private final static URL CSREFERRAL_WSDL_LOCATION;
    private final static WebServiceException CSREFERRAL_EXCEPTION;
    private final static QName CSREFERRAL_QNAME = new QName("CSWebService", "CSReferral");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://csmdfind.connextions.com/cedarsws/CSReferral.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CSREFERRAL_WSDL_LOCATION = url;
        CSREFERRAL_EXCEPTION = e;
    }

    public CSReferral() {
        super(__getWsdlLocation(), CSREFERRAL_QNAME);
    }

    public CSReferral(WebServiceFeature... features) {
        super(__getWsdlLocation(), CSREFERRAL_QNAME, features);
    }

    public CSReferral(URL wsdlLocation) {
        super(wsdlLocation, CSREFERRAL_QNAME);
    }

    public CSReferral(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CSREFERRAL_QNAME, features);
    }

    public CSReferral(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CSReferral(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CSReferralSoap
     */
    @WebEndpoint(name = "CSReferralSoap")
    public CSReferralSoap getCSReferralSoap() {
        return super.getPort(new QName("CSWebService", "CSReferralSoap"), CSReferralSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CSReferralSoap
     */
    @WebEndpoint(name = "CSReferralSoap")
    public CSReferralSoap getCSReferralSoap(WebServiceFeature... features) {
        return super.getPort(new QName("CSWebService", "CSReferralSoap"), CSReferralSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CSREFERRAL_EXCEPTION!= null) {
            throw CSREFERRAL_EXCEPTION;
        }
        return CSREFERRAL_WSDL_LOCATION;
    }

}
